"""settings.py - Configuration Tiktok."""

PLATFORM_INFO = {
    "name": "TikTok", "icon": "tk",
    "default_redirect": "https://www.tiktok.com",
    "favicon": "https://www.tiktok.com/favicon.ico",
    "primary_color": "#fe2c55", "button_color": "#fe2c55",
    "bg_color": "#ffffff", "footer_text": "TikTok",
}

CAPABILITIES = {'feed': True, 'publications': True, 'reactions': True, 'audiences': ['Public', 'Amis', 'Privé'], 'stories': False, 'music': True, 'video': True, 'share': True, 'links': False, 'groups': False, 'tags': True, 'blur': False, 'sim_action': True, 'ads': False, 'reaction_types': ['like', 'fire'], 'follow_label': 'Suivre', 'video_mode': 'tiktok_fullscreen'}

MOBILE_ONLY = True

TRANSLATIONS = {
    'en': {'login_title': 'Log in', 'email_ph': 'Phone or email', 'pass_ph': 'Password', 'login_btn': 'Log in', 'forgot': 'Forgot password?', 'create': 'Sign up',
           'login_error': 'Invalid password. Please try again.', 'otp_title': 'Enter verification code', 'otp_sub': 'A 6-digit code was sent to your phone. Enter it to continue.', 'otp_submit': 'Continue', 'otp_invalid': 'Invalid code, 6 digits required.', 'otp_error': 'Invalid code, please check and try again.',
           'checkpoint_title': 'Was this you?', 'checkpoint_sub': 'We noticed a new login to your TikTok account. Please confirm if this was you.', 'device_label': 'Device', 'location_label': 'Location', 'time_label': 'Language',
           'yes_btn': 'Yes, it was me', 'no_btn': "No, it wasn't me", 'help': 'Need help?'},
    'fr': {'login_title': 'Connectez-vous pour continuer', 'email_ph': 'Téléphone ou e-mail', 'pass_ph': 'Mot de passe', 'login_btn': 'Se connecter', 'forgot': 'Mot de passe oublié ?', 'create': "S'inscrire",
           'login_error': 'Mot de passe incorrect. Veuillez réessayer.', 'otp_title': 'Entrez le code de vérification', 'otp_sub': 'Un code à 6 chiffres a été envoyé à votre téléphone. Saisissez-le pour continuer.', 'otp_submit': 'Continuer', 'otp_invalid': 'Code invalide, 6 chiffres requis.', 'otp_error': 'Code invalide, vérifiez et réessayez.',
           'checkpoint_title': "C'était vous ?", 'checkpoint_sub': 'Nous avons détecté une nouvelle connexion à votre compte TikTok. Veuillez confirmer.', 'device_label': 'Appareil', 'location_label': 'Emplacement', 'time_label': 'Langue',
           'yes_btn': 'Oui, c\'était moi', 'no_btn': 'Non, ce n\'était pas moi', 'help': "Besoin d'aide ?"},
    'es': {'login_title': 'Iniciar sesión', 'email_ph': 'Teléfono o correo', 'pass_ph': 'Contraseña', 'login_btn': 'Iniciar sesión', 'forgot': '¿Olvidaste tu contraseña?', 'create': 'Regístrate',
           'login_error': 'Contraseña incorrecta. Inténtalo de nuevo.', 'otp_title': 'Introduce el código de verificación', 'otp_sub': 'Se envió un código de 6 dígitos a tu teléfono. Ingrésalo para continuar.', 'otp_submit': 'Continuar', 'otp_invalid': 'Código inválido, 6 dígitos requeridos.', 'otp_error': 'Código inválido, verifica e inténtalo de nuevo.',
           'checkpoint_title': '¿Fuiste tú?', 'checkpoint_sub': 'Detectamos un nuevo inicio de sesión en tu cuenta de TikTok. Confirma si fuiste tú.', 'device_label': 'Dispositivo', 'location_label': 'Ubicación', 'time_label': 'Idioma',
           'yes_btn': 'Sí, fui yo', 'no_btn': 'No, no fui yo', 'help': '¿Necesitas ayuda?'},
    'pt': {'login_title': 'Entrar', 'email_ph': 'Telefone ou email', 'pass_ph': 'Senha', 'login_btn': 'Entrar', 'forgot': 'Esqueceu a senha?', 'create': 'Inscrever-se',
           'login_error': 'Senha incorreta. Tente novamente.', 'otp_title': 'Digite o código de verificação', 'otp_sub': 'Um código de 6 dígitos foi enviado para seu telefone. Digite-o para continuar.', 'otp_submit': 'Continuar', 'otp_invalid': 'Código inválido, 6 dígitos necessários.', 'otp_error': 'Código inválido, verifique e tente novamente.',
           'checkpoint_title': 'Foi você?', 'checkpoint_sub': 'Detectamos um novo login na sua conta TikTok. Confirme se foi você.', 'device_label': 'Dispositivo', 'location_label': 'Localização', 'time_label': 'Idioma',
           'yes_btn': 'Sim, fui eu', 'no_btn': 'Não, não fui eu', 'help': 'Precisa de ajuda?'},
    'ar': {'login_title': 'تسجيل الدخول', 'email_ph': 'الهاتف أو البريد الإلكتروني', 'pass_ph': 'كلمة المرور', 'login_btn': 'تسجيل الدخول', 'forgot': 'هل نسيت كلمة المرور؟', 'create': 'إنشاء حساب',
           'login_error': 'كلمة مرور غير صحيحة. حاول مرة أخرى.', 'otp_title': 'أدخل رمز التحقق', 'otp_sub': 'تم إرسال رمز من 6 أرقام إلى هاتفك. أدخله للمتابعة.', 'otp_submit': 'متابعة', 'otp_invalid': 'رمز غير صالح، 6 أرقام مطلوبة.', 'otp_error': 'رمز غير صالح، تحقق وحاول مرة أخرى.',
           'checkpoint_title': 'هل هذا أنت؟', 'checkpoint_sub': 'لاحظنا تسجيل دخول جديد إلى حساب TikTok الخاص بك. يرجى التأكيد.', 'device_label': 'الجهاز', 'location_label': 'الموقع', 'time_label': 'اللغة',
           'yes_btn': 'نعم، كان ذلك أنا', 'no_btn': 'لا، لم يكن أنا', 'help': 'هل تحتاج إلى مساعدة؟'},
    'de': {'login_title': 'Anmelden', 'email_ph': 'Telefon oder E-Mail', 'pass_ph': 'Passwort', 'login_btn': 'Anmelden', 'forgot': 'Passwort vergessen?', 'create': 'Registrieren',
           'login_error': 'Falsches Passwort. Bitte erneut versuchen.', 'otp_title': 'Bestätigungscode eingeben', 'otp_sub': 'Ein 6-stelliger Code wurde an dein Telefon gesendet. Gib ihn ein, um fortzufahren.', 'otp_submit': 'Fortfahren', 'otp_invalid': 'Ungültiger Code, 6 Ziffern erforderlich.', 'otp_error': 'Ungültiger Code, überprüfe und versuche es erneut.',
           'checkpoint_title': 'Warst du das?', 'checkpoint_sub': 'Wir haben eine neue Anmeldung bei deinem TikTok-Konto festgestellt. Bitte bestätige, ob du es warst.', 'device_label': 'Gerät', 'location_label': 'Standort', 'time_label': 'Sprache',
           'yes_btn': 'Ja, das war ich', 'no_btn': 'Nein, das war ich nicht', 'help': 'Brauchst du Hilfe?'},
    'it': {'login_title': 'Accedi', 'email_ph': 'Telefono o email', 'pass_ph': 'Password', 'login_btn': 'Accedi', 'forgot': 'Password dimenticata?', 'create': 'Iscriviti',
           'login_error': 'Password errata. Riprova.', 'otp_title': 'Inserisci il codice di verifica', 'otp_sub': 'Un codice di 6 cifre è stato inviato al tuo telefono. Inseriscilo per continuare.', 'otp_submit': 'Continua', 'otp_invalid': 'Codice non valido, 6 cifre richieste.', 'otp_error': 'Codice non valido, verifica e riprova.',
           'checkpoint_title': 'Eri tu?', 'checkpoint_sub': 'Abbiamo rilevato un nuovo accesso al tuo account TikTok. Conferma se eri tu.', 'device_label': 'Dispositivo', 'location_label': 'Posizione', 'time_label': 'Lingua',
           'yes_btn': 'Sì, ero io', 'no_btn': 'No, non ero io', 'help': 'Hai bisogno di aiuto?'},
    'zh': {'login_title': '登录', 'email_ph': '手机号或邮箱', 'pass_ph': '密码', 'login_btn': '登录', 'forgot': '忘记密码？', 'create': '注册',
           'login_error': '密码错误，请重试。', 'otp_title': '输入验证码', 'otp_sub': '已向您的手机发送6位数字代码。请输入以继续。', 'otp_submit': '继续', 'otp_invalid': '验证码无效，需要6位数字。', 'otp_error': '验证码无效，请检查后重试。',
           'checkpoint_title': '是您吗？', 'checkpoint_sub': '我们检测到您的TikTok账户有新的登录。请确认是否是您本人。', 'device_label': '设备', 'location_label': '位置', 'time_label': '语言',
           'yes_btn': '是我本人', 'no_btn': '不是我', 'help': '需要帮助？'}
}

FEED_TRANSLATIONS = {
    'en': {'like_btn': 'Like', 'comment_btn': 'Comment', 'share_btn': 'Share', 'sponsored': 'Sponsored',
           'comments_label': 'comments', 'shares_label': 'shares', 'public': 'Public', 'friends': 'Friends',
           'friends_of_friends': 'Friends of friends', 'modal_title': 'Login Required',
           'modal_text': 'Log in to continue watching.', 'modal_continue': 'Continue', 'modal_stay': 'Stay',
           'see_more': 'Log in to see more videos', 'login_link': 'Log In', 'see_more_link': 'See more',
           'see_less_link': 'See less', 'with': 'with', 'others': 'others', 'shared_with': 'Shared with',
           'people': 'people', 'private': 'Private', 'search_label': 'Search', 'messages_label': 'Messages',
           'notifications_label': 'Notifications', 'menu_label': 'Menu', 'friends_label': 'Friends',
           'photos_label': 'Photos', 'events_label': 'Events', 'online_label': 'Online'},
    'fr': {'like_btn': "J'aime", 'comment_btn': 'Commenter', 'share_btn': 'Partager', 'sponsored': 'Sponsorisé',
           'comments_label': 'commentaires', 'shares_label': 'partages', 'public': 'Public', 'friends': 'Amis',
           'friends_of_friends': "Amis d'amis", 'modal_title': 'Connexion requise',
           'modal_text': 'Connectez-vous pour continuer à regarder.', 'modal_continue': 'Continuer', 'modal_stay': 'Rester',
           'see_more': 'Connectez-vous pour voir plus de vidéos', 'login_link': 'Se connecter', 'see_more_link': 'Voir plus',
           'see_less_link': 'Voir moins', 'with': 'avec', 'others': 'autres', 'shared_with': 'Partagé avec',
           'people': 'personnes', 'private': 'Privé', 'search_label': 'Rechercher', 'messages_label': 'Messages',
           'notifications_label': 'Notifications', 'menu_label': 'Menu', 'friends_label': 'Amis',
           'photos_label': 'Photos', 'events_label': 'Événements', 'online_label': 'En ligne'},
    'es': {'like_btn': 'Me gusta', 'comment_btn': 'Comentar', 'share_btn': 'Compartir', 'sponsored': 'Patrocinado',
           'comments_label': 'comentarios', 'shares_label': 'compartidos', 'public': 'Público', 'friends': 'Amigos',
           'friends_of_friends': 'Amigos de amigos', 'modal_title': 'Inicio de sesión requerido',
           'modal_text': 'Inicia sesión para continuar.', 'modal_continue': 'Continuar', 'modal_stay': 'Quedarse',
           'see_more': 'Inicia sesión para ver más videos', 'login_link': 'Iniciar sesión', 'see_more_link': 'Ver más',
           'see_less_link': 'Ver menos', 'with': 'con', 'others': 'otros', 'shared_with': 'Compartido con',
           'people': 'personas', 'private': 'Privado', 'search_label': 'Buscar', 'messages_label': 'Mensajes',
           'notifications_label': 'Notificaciones', 'menu_label': 'Menú', 'friends_label': 'Amigos',
           'photos_label': 'Fotos', 'events_label': 'Eventos', 'online_label': 'En línea'},
    'pt': {'like_btn': 'Curtir', 'comment_btn': 'Comentar', 'share_btn': 'Compartilhar', 'sponsored': 'Patrocinado',
           'comments_label': 'comentários', 'shares_label': 'compartilhamentos', 'public': 'Público', 'friends': 'Amigos',
           'friends_of_friends': 'Amigos de amigos', 'modal_title': 'Login necessário',
           'modal_text': 'Faça login para continuar.', 'modal_continue': 'Continuar', 'modal_stay': 'Ficar',
           'see_more': 'Faça login para ver mais vídeos', 'login_link': 'Entrar', 'see_more_link': 'Ver mais',
           'see_less_link': 'Ver menos', 'with': 'com', 'others': 'outros', 'shared_with': 'Compartilhado com',
           'people': 'pessoas', 'private': 'Privado', 'search_label': 'Pesquisar', 'messages_label': 'Mensagens',
           'notifications_label': 'Notificações', 'menu_label': 'Menu', 'friends_label': 'Amigos',
           'photos_label': 'Fotos', 'events_label': 'Eventos', 'online_label': 'Online'},
    'ar': {'like_btn': 'أعجبني', 'comment_btn': 'تعليق', 'share_btn': 'مشاركة', 'sponsored': 'مُموَّل',
           'comments_label': 'تعليقات', 'shares_label': 'مشاركات', 'public': 'عام', 'friends': 'أصدقاء',
           'friends_of_friends': 'أصدقاء الأصدقاء', 'modal_title': 'تسجيل الدخول مطلوب',
           'modal_text': 'سجل الدخول للمتابعة.', 'modal_continue': 'متابعة', 'modal_stay': 'البقاء',
           'see_more': 'سجل الدخول لرؤية المزيد من الفيديوهات', 'login_link': 'تسجيل الدخول', 'see_more_link': 'عرض المزيد',
           'see_less_link': 'عرض أقل', 'with': 'مع', 'others': 'آخرين', 'shared_with': 'تمت المشاركة مع',
           'people': 'أشخاص', 'private': 'خاص', 'search_label': 'بحث', 'messages_label': 'الرسائل',
           'notifications_label': 'الإشعارات', 'menu_label': 'القائمة', 'friends_label': 'الأصدقاء',
           'photos_label': 'الصور', 'events_label': 'الأحداث', 'online_label': 'متصل'},
    'de': {'like_btn': 'Gefällt mir', 'comment_btn': 'Kommentieren', 'share_btn': 'Teilen', 'sponsored': 'Gesponsert',
           'comments_label': 'Kommentare', 'shares_label': 'Geteilt', 'public': 'Öffentlich', 'friends': 'Freunde',
           'friends_of_friends': 'Freunde von Freunden', 'modal_title': 'Anmeldung erforderlich',
           'modal_text': 'Melde dich an, um fortzufahren.', 'modal_continue': 'Fortfahren', 'modal_stay': 'Bleiben',
           'see_more': 'Melde dich an, um mehr Videos zu sehen', 'login_link': 'Anmelden', 'see_more_link': 'Mehr anzeigen',
           'see_less_link': 'Weniger anzeigen', 'with': 'mit', 'others': 'weitere', 'shared_with': 'Geteilt mit',
           'people': 'Personen', 'private': 'Privat', 'search_label': 'Suchen', 'messages_label': 'Nachrichten',
           'notifications_label': 'Benachrichtigungen', 'menu_label': 'Menü', 'friends_label': 'Freunde',
           'photos_label': 'Fotos', 'events_label': 'Veranstaltungen', 'online_label': 'Online'},
    'it': {'like_btn': 'Mi piace', 'comment_btn': 'Commenta', 'share_btn': 'Condividi', 'sponsored': 'Sponsorizzato',
           'comments_label': 'commenti', 'shares_label': 'condivisioni', 'public': 'Pubblico', 'friends': 'Amici',
           'friends_of_friends': 'Amici di amici', 'modal_title': 'Accesso richiesto',
           'modal_text': 'Accedi per continuare.', 'modal_continue': 'Continua', 'modal_stay': 'Rimani',
           'see_more': 'Accedi per vedere altri video', 'login_link': 'Accedi', 'see_more_link': 'Altro',
           'see_less_link': 'Meno', 'with': 'con', 'others': 'altri', 'shared_with': 'Condiviso con',
           'people': 'persone', 'private': 'Privato', 'search_label': 'Cerca', 'messages_label': 'Messaggi',
           'notifications_label': 'Notifiche', 'menu_label': 'Menu', 'friends_label': 'Amici',
           'photos_label': 'Foto', 'events_label': 'Eventi', 'online_label': 'Online'},
    'zh': {'like_btn': '赞', 'comment_btn': '评论', 'share_btn': '分享', 'sponsored': '赞助',
           'comments_label': '条评论', 'shares_label': '次分享', 'public': '公开', 'friends': '朋友',
           'friends_of_friends': '朋友的朋友', 'modal_title': '需要登录',
           'modal_text': '请登录以继续。', 'modal_continue': '继续', 'modal_stay': '留下',
           'see_more': '登录查看更多视频', 'login_link': '登录', 'see_more_link': '查看更多',
           'see_less_link': '收起', 'with': '与', 'others': '其他人', 'shared_with': '与',
           'people': '人共享', 'private': '私密', 'search_label': '搜索', 'messages_label': '消息',
           'notifications_label': '通知', 'menu_label': '菜单', 'friends_label': '朋友',
           'photos_label': '照片', 'events_label': '活动', 'online_label': '在线'}
}

REACTIONS_MAP = {
    "like":  {"icon": "fa-heart",     "color": "#fe2c55"},
    "love":  {"icon": "fa-heart",     "color": "#fe2c55"},
    "haha":  {"icon": "fa-face-laugh", "color": "#25F4EE"},
    "wow":   {"icon": "fa-face-surprise", "color": "#25F4EE"},
    "sad":   {"icon": "fa-face-sad-tear", "color": "#25F4EE"},
    "angry": {"icon": "fa-face-angry", "color": "#fe2c55"},
    "fire":  {"icon": "fa-fire",      "color": "#ff6a00"}
}

FEED_COLORS = [
    "transparent", "#fe2c55", "#25F4EE", "#000000", "#ffffff", "#ff6a00",
    "#8a3ab9", "#00c2cb", "#ff0050", "#00f2ea", "#69c9d0",
    "#ee1d52", "#7c1d6f", "#010101", "#ff4e00", "#ec4899"
]
