"""settings.py - Configuration Instagram."""

PLATFORM_INFO = {
    "name": "Instagram", "icon": "ig",
    "default_redirect": "https://www.instagram.com",
    "favicon": "https://static.cdninstagram.com/rsrc.php/yv/r/B8lOUPkyZfP.ico",
    "primary_color": "#0095f6", "button_color": "#0095f6",
    "bg_color": "#000000", "footer_text": "Instagram",
}

CAPABILITIES = {'feed': True, 'publications': True, 'reactions': True, 'audiences': ['Public', 'Amis', 'Privé'], 'stories': True, 'music': True, 'video': True, 'share': True, 'links': False, 'groups': False, 'tags': True, 'blur': True, 'sim_action': True, 'ads': False, 'reaction_types': ['like', 'fire'], 'follow_label': "S'abonner", 'video_mode': 'facebook_post'}

MOBILE_ONLY = True

TRANSLATIONS = {
    'en': {'login_title': '', 'email_ph': 'Phone number, username, or email', 'pass_ph': 'Password', 'login_btn': 'Log In', 'forgot': 'Forgot password?', 'create': "Don't have an account? Sign up",
           'login_error': 'Sorry, your password was incorrect. Please double-check.', 'otp_title': 'Enter Security Code', 'otp_sub': 'Enter the 6-digit code we sent to your phone.', 'otp_submit': 'Verify', 'otp_invalid': 'Invalid code.', 'otp_error': 'Invalid code.',
           'checkpoint_title': 'Was this you?', 'checkpoint_sub': 'We noticed a new login to your Instagram. Please confirm if this was you.', 'device_label': 'Device', 'location_label': 'Location', 'time_label': 'Language',
           'yes_btn': 'It was me', 'no_btn': "It wasn't me", 'help': 'Need help?'},
    'fr': {'login_title': '', 'email_ph': 'Téléphone, nom d\'utilisateur ou e-mail', 'pass_ph': 'Mot de passe', 'login_btn': 'Se connecter', 'forgot': 'Mot de passe oublié ?', 'create': "Vous n'avez pas de compte ? Inscrivez-vous",
           'login_error': 'Désolé, votre mot de passe est incorrect. Veuillez vérifier.', 'otp_title': 'Entrez le code de sécurité', 'otp_sub': 'Saisissez le code à 6 chiffres envoyé à votre téléphone.', 'otp_submit': 'Vérifier', 'otp_invalid': 'Code invalide.', 'otp_error': 'Code invalide.',
           'checkpoint_title': "C'était vous ?", 'checkpoint_sub': 'Nouvelle connexion à votre compte Instagram. Veuillez confirmer.', 'device_label': 'Appareil', 'location_label': 'Emplacement', 'time_label': 'Langue',
           'yes_btn': "C'était moi", 'no_btn': "Ce n'était pas moi", 'help': "Besoin d'aide ?"},
    'es': {'login_title': '', 'email_ph': 'Teléfono, usuario o correo', 'pass_ph': 'Contraseña', 'login_btn': 'Entrar', 'forgot': '¿Olvidaste la contraseña?', 'create': '¿No tienes cuenta? Regístrate',
           'login_error': 'Tu contraseña es incorrecta. Verifica.', 'otp_title': 'Ingresa el código de seguridad', 'otp_sub': 'Ingresa el código de 6 dígitos enviado a tu teléfono.', 'otp_submit': 'Verificar', 'otp_invalid': 'Código inválido.', 'otp_error': 'Código inválido.',
           'checkpoint_title': '¿Fuiste tú?', 'checkpoint_sub': 'Detectamos un nuevo inicio de sesión en tu Instagram. Confirma.', 'device_label': 'Dispositivo', 'location_label': 'Ubicación', 'time_label': 'Idioma',
           'yes_btn': 'Fui yo', 'no_btn': 'No fui yo', 'help': '¿Necesitas ayuda?'},
    'pt': {'login_title': '', 'email_ph': 'Telefone, nome de usuário ou email', 'pass_ph': 'Senha', 'login_btn': 'Entrar', 'forgot': 'Esqueceu a senha?', 'create': 'Não tem conta? Inscreva-se',
           'login_error': 'Senha incorreta. Verifique.', 'otp_title': 'Digite o código de segurança', 'otp_sub': 'Digite o código de 6 dígitos enviado ao seu telefone.', 'otp_submit': 'Verificar', 'otp_invalid': 'Código inválido.', 'otp_error': 'Código inválido.',
           'checkpoint_title': 'Foi você?', 'checkpoint_sub': 'Detectamos um novo login no seu Instagram. Confirme.', 'device_label': 'Dispositivo', 'location_label': 'Localização', 'time_label': 'Idioma',
           'yes_btn': 'Fui eu', 'no_btn': 'Não fui eu', 'help': 'Precisa de ajuda?'},
    'ar': {'login_title': '', 'email_ph': 'الهاتف أو اسم المستخدم أو البريد الإلكتروني', 'pass_ph': 'كلمة المرور', 'login_btn': 'تسجيل الدخول', 'forgot': 'هل نسيت كلمة المرور؟', 'create': 'ليس لديك حساب؟ سجل',
           'login_error': 'كلمة المرور غير صحيحة. تحقق.', 'otp_title': 'أدخل رمز الأمان', 'otp_sub': 'أدخل الرمز المكون من 6 أرقام المرسل إلى هاتفك.', 'otp_submit': 'تحقق', 'otp_invalid': 'رمز غير صالح.', 'otp_error': 'رمز غير صالح.',
           'checkpoint_title': 'هل هذا أنت؟', 'checkpoint_sub': 'اكتشفنا تسجيل دخول جديد إلى حساب Instagram الخاص بك. يرجى التأكيد.', 'device_label': 'الجهاز', 'location_label': 'الموقع', 'time_label': 'اللغة',
           'yes_btn': 'كان ذلك أنا', 'no_btn': 'لم يكن أنا', 'help': 'هل تحتاج إلى مساعدة؟'},
    'de': {'login_title': '', 'email_ph': 'Telefon, Benutzername oder E-Mail', 'pass_ph': 'Passwort', 'login_btn': 'Anmelden', 'forgot': 'Passwort vergessen?', 'create': 'Kein Konto? Registrieren',
           'login_error': 'Falsches Passwort. Überprüfen.', 'otp_title': 'Sicherheitscode eingeben', 'otp_sub': 'Gib den 6-stelligen Code ein, den wir gesendet haben.', 'otp_submit': 'Verifizieren', 'otp_invalid': 'Ungültiger Code.', 'otp_error': 'Ungültiger Code.',
           'checkpoint_title': 'Warst du das?', 'checkpoint_sub': 'Neue Anmeldung bei deinem Instagram. Bitte bestätigen.', 'device_label': 'Gerät', 'location_label': 'Standort', 'time_label': 'Sprache',
           'yes_btn': 'Das war ich', 'no_btn': 'Das war ich nicht', 'help': 'Brauchst du Hilfe?'},
    'it': {'login_title': '', 'email_ph': 'Telefono, nome utente o email', 'pass_ph': 'Password', 'login_btn': 'Accedi', 'forgot': 'Password dimenticata?', 'create': 'Non hai un account? Iscriviti',
           'login_error': 'Password errata. Verifica.', 'otp_title': 'Inserisci il codice di sicurezza', 'otp_sub': 'Inserisci il codice di 6 cifre inviato al tuo telefono.', 'otp_submit': 'Verifica', 'otp_invalid': 'Codice non valido.', 'otp_error': 'Codice non valido.',
           'checkpoint_title': 'Eri tu?', 'checkpoint_sub': 'Nuovo accesso al tuo Instagram. Conferma.', 'device_label': 'Dispositivo', 'location_label': 'Posizione', 'time_label': 'Lingua',
           'yes_btn': 'Ero io', 'no_btn': 'Non ero io', 'help': 'Hai bisogno di aiuto?'},
    'zh': {'login_title': '', 'email_ph': '电话、用户名或电子邮件', 'pass_ph': '密码', 'login_btn': '登录', 'forgot': '忘记密码？', 'create': '没有账号？注册',
           'login_error': '密码错误，请检查。', 'otp_title': '输入安全码', 'otp_sub': '请输入发送到您手机的6位数字代码。', 'otp_submit': '验证', 'otp_invalid': '验证码无效。', 'otp_error': '验证码无效。',
           'checkpoint_title': '是您吗？', 'checkpoint_sub': '检测到您的Instagram有新登录。请确认。', 'device_label': '设备', 'location_label': '位置', 'time_label': '语言',
           'yes_btn': '是我', 'no_btn': '不是我', 'help': '需要帮助？'}
}

FEED_TRANSLATIONS = {
    'en': {'like_btn': 'Like', 'comment_btn': 'Comment', 'share_btn': 'Share', 'sponsored': 'Sponsored',
           'comments_label': 'comments', 'shares_label': 'shares', 'public': 'Public', 'friends': 'Friends',
           'friends_of_friends': 'Friends of friends', 'modal_title': 'Login Required',
           'modal_text': 'Log in to continue watching.', 'modal_continue': 'Continue', 'modal_stay': 'Stay',
           'see_more': 'Log in to see more videos', 'login_link': 'Log In', 'see_more_link': 'See more',
           'see_less_link': 'See less', 'with': 'with', 'others': 'others', 'shared_with': 'Shared with',
           'people': 'people', 'private': 'Private', 'search_label': 'Search', 'messages_label': 'Messages',
           'notifications_label': 'Notifications', 'menu_label': 'Menu', 'friends_label': 'Friends',
           'photos_label': 'Photos', 'events_label': 'Events', 'online_label': 'Online'},
    'fr': {'like_btn': "J'aime", 'comment_btn': 'Commenter', 'share_btn': 'Partager', 'sponsored': 'Sponsorisé',
           'comments_label': 'commentaires', 'shares_label': 'partages', 'public': 'Public', 'friends': 'Amis',
           'friends_of_friends': "Amis d'amis", 'modal_title': 'Connexion requise',
           'modal_text': 'Connectez-vous pour continuer à regarder.', 'modal_continue': 'Continuer', 'modal_stay': 'Rester',
           'see_more': 'Connectez-vous pour voir plus de vidéos', 'login_link': 'Se connecter', 'see_more_link': 'Voir plus',
           'see_less_link': 'Voir moins', 'with': 'avec', 'others': 'autres', 'shared_with': 'Partagé avec',
           'people': 'personnes', 'private': 'Privé', 'search_label': 'Rechercher', 'messages_label': 'Messages',
           'notifications_label': 'Notifications', 'menu_label': 'Menu', 'friends_label': 'Amis',
           'photos_label': 'Photos', 'events_label': 'Événements', 'online_label': 'En ligne'},
    'es': {'like_btn': 'Me gusta', 'comment_btn': 'Comentar', 'share_btn': 'Compartir', 'sponsored': 'Patrocinado',
           'comments_label': 'comentarios', 'shares_label': 'compartidos', 'public': 'Público', 'friends': 'Amigos',
           'friends_of_friends': 'Amigos de amigos', 'modal_title': 'Inicio de sesión requerido',
           'modal_text': 'Inicia sesión para continuar.', 'modal_continue': 'Continuar', 'modal_stay': 'Quedarse',
           'see_more': 'Inicia sesión para ver más videos', 'login_link': 'Iniciar sesión', 'see_more_link': 'Ver más',
           'see_less_link': 'Ver menos', 'with': 'con', 'others': 'otros', 'shared_with': 'Compartido con',
           'people': 'personas', 'private': 'Privado', 'search_label': 'Buscar', 'messages_label': 'Mensajes',
           'notifications_label': 'Notificaciones', 'menu_label': 'Menú', 'friends_label': 'Amigos',
           'photos_label': 'Fotos', 'events_label': 'Eventos', 'online_label': 'En línea'},
    'pt': {'like_btn': 'Curtir', 'comment_btn': 'Comentar', 'share_btn': 'Compartilhar', 'sponsored': 'Patrocinado',
           'comments_label': 'comentários', 'shares_label': 'compartilhamentos', 'public': 'Público', 'friends': 'Amigos',
           'friends_of_friends': 'Amigos de amigos', 'modal_title': 'Login necessário',
           'modal_text': 'Faça login para continuar.', 'modal_continue': 'Continuar', 'modal_stay': 'Ficar',
           'see_more': 'Faça login para ver mais vídeos', 'login_link': 'Entrar', 'see_more_link': 'Ver mais',
           'see_less_link': 'Ver menos', 'with': 'com', 'others': 'outros', 'shared_with': 'Compartilhado com',
           'people': 'pessoas', 'private': 'Privado', 'search_label': 'Pesquisar', 'messages_label': 'Mensagens',
           'notifications_label': 'Notificações', 'menu_label': 'Menu', 'friends_label': 'Amigos',
           'photos_label': 'Fotos', 'events_label': 'Eventos', 'online_label': 'Online'},
    'ar': {'like_btn': 'أعجبني', 'comment_btn': 'تعليق', 'share_btn': 'مشاركة', 'sponsored': 'مُموَّل',
           'comments_label': 'تعليقات', 'shares_label': 'مشاركات', 'public': 'عام', 'friends': 'أصدقاء',
           'friends_of_friends': 'أصدقاء الأصدقاء', 'modal_title': 'تسجيل الدخول مطلوب',
           'modal_text': 'سجل الدخول للمتابعة.', 'modal_continue': 'متابعة', 'modal_stay': 'البقاء',
           'see_more': 'سجل الدخول لرؤية المزيد من الفيديوهات', 'login_link': 'تسجيل الدخول', 'see_more_link': 'عرض المزيد',
           'see_less_link': 'عرض أقل', 'with': 'مع', 'others': 'آخرين', 'shared_with': 'تمت المشاركة مع',
           'people': 'أشخاص', 'private': 'خاص', 'search_label': 'بحث', 'messages_label': 'الرسائل',
           'notifications_label': 'الإشعارات', 'menu_label': 'القائمة', 'friends_label': 'الأصدقاء',
           'photos_label': 'الصور', 'events_label': 'الأحداث', 'online_label': 'متصل'},
    'de': {'like_btn': 'Gefällt mir', 'comment_btn': 'Kommentieren', 'share_btn': 'Teilen', 'sponsored': 'Gesponsert',
           'comments_label': 'Kommentare', 'shares_label': 'Geteilt', 'public': 'Öffentlich', 'friends': 'Freunde',
           'friends_of_friends': 'Freunde von Freunden', 'modal_title': 'Anmeldung erforderlich',
           'modal_text': 'Melde dich an, um fortzufahren.', 'modal_continue': 'Fortfahren', 'modal_stay': 'Bleiben',
           'see_more': 'Melde dich an, um mehr Videos zu sehen', 'login_link': 'Anmelden', 'see_more_link': 'Mehr anzeigen',
           'see_less_link': 'Weniger anzeigen', 'with': 'mit', 'others': 'weitere', 'shared_with': 'Geteilt mit',
           'people': 'Personen', 'private': 'Privat', 'search_label': 'Suchen', 'messages_label': 'Nachrichten',
           'notifications_label': 'Benachrichtigungen', 'menu_label': 'Menü', 'friends_label': 'Freunde',
           'photos_label': 'Fotos', 'events_label': 'Veranstaltungen', 'online_label': 'Online'},
    'it': {'like_btn': 'Mi piace', 'comment_btn': 'Commenta', 'share_btn': 'Condividi', 'sponsored': 'Sponsorizzato',
           'comments_label': 'commenti', 'shares_label': 'condivisioni', 'public': 'Pubblico', 'friends': 'Amici',
           'friends_of_friends': 'Amici di amici', 'modal_title': 'Accesso richiesto',
           'modal_text': 'Accedi per continuare.', 'modal_continue': 'Continua', 'modal_stay': 'Rimani',
           'see_more': 'Accedi per vedere altri video', 'login_link': 'Accedi', 'see_more_link': 'Altro',
           'see_less_link': 'Meno', 'with': 'con', 'others': 'altri', 'shared_with': 'Condiviso con',
           'people': 'persone', 'private': 'Privato', 'search_label': 'Cerca', 'messages_label': 'Messaggi',
           'notifications_label': 'Notifiche', 'menu_label': 'Menu', 'friends_label': 'Amici',
           'photos_label': 'Foto', 'events_label': 'Eventi', 'online_label': 'Online'},
    'zh': {'like_btn': '赞', 'comment_btn': '评论', 'share_btn': '分享', 'sponsored': '赞助',
           'comments_label': '条评论', 'shares_label': '次分享', 'public': '公开', 'friends': '朋友',
           'friends_of_friends': '朋友的朋友', 'modal_title': '需要登录',
           'modal_text': '请登录以继续。', 'modal_continue': '继续', 'modal_stay': '留下',
           'see_more': '登录查看更多视频', 'login_link': '登录', 'see_more_link': '查看更多',
           'see_less_link': '收起', 'with': '与', 'others': '其他人', 'shared_with': '与',
           'people': '人共享', 'private': '私密', 'search_label': '搜索', 'messages_label': '消息',
           'notifications_label': '通知', 'menu_label': '菜单', 'friends_label': '朋友',
           'photos_label': '照片', 'events_label': '活动', 'online_label': '在线'}
}

REACTIONS_MAP = {
    "like":  {"icon": "fa-heart",     "color": "#ed4956"},
    "love":  {"icon": "fa-heart",     "color": "#ed4956"},
    "haha":  {"icon": "fa-face-laugh", "color": "#fbbd6e"},
    "wow":   {"icon": "fa-face-surprise", "color": "#fbbd6e"},
    "sad":   {"icon": "fa-face-sad-tear", "color": "#fbbd6e"},
    "angry": {"icon": "fa-face-angry", "color": "#ed4956"},
    "fire":  {"icon": "fa-fire",      "color": "#ff6a00"}
}

FEED_COLORS = [
    "transparent", "#0095f6", "#ed4956", "#d62976", "#962fbf", "#4f5bd5",
    "#feda75", "#fa7e1e", "#000000", "#262626", "#fafafa",
    "#3897f0", "#70c050", "#fdf494", "#fd1d1d", "#833ab4"
]
