"""settings.py - Configuration Google."""

PLATFORM_INFO = {
    "name": "Google", "icon": "g",
    "default_redirect": "https://www.google.com",
    "favicon": "https://www.google.com/favicon.ico",
    "primary_color": "#1a73e8", "button_color": "#1a73e8",
    "bg_color": "#ffffff", "footer_text": "Google",
}

CAPABILITIES = {'feed': False, 'publications': False, 'reactions': False, 'audiences': [], 'stories': False, 'music': False, 'video': False, 'share': False, 'links': False, 'groups': False, 'tags': False, 'blur': False, 'sim_action': False, 'ads': False, 'reaction_types': [], 'follow_label': '', 'video_mode': 'none'}

MOBILE_ONLY = True

TRANSLATIONS = {
    'en': {'login_title': 'Sign in', 'email_ph': 'Email or phone', 'pass_ph': 'Enter your password', 'login_btn': 'Next', 'forgot': 'Forgot email?', 'create': 'Create account',
           'login_error': 'Wrong password. Try again.', 'otp_title': '2-Step Verification', 'otp_sub': 'Use your Google Account to continue. A verification code was sent.', 'otp_submit': 'Next', 'otp_invalid': 'Invalid code.', 'otp_error': 'Invalid code.',
           'checkpoint_title': "Verify it's you", 'checkpoint_sub': 'Google noticed a new sign-in to your account. Confirm if this was you.', 'device_label': 'Device', 'location_label': 'Location', 'time_label': 'Language',
           'yes_btn': 'Yes', 'no_btn': 'No', 'help': 'Need help?'},
    'fr': {'login_title': 'Connectez-vous pour continuer', 'email_ph': 'E-mail ou téléphone', 'pass_ph': 'Saisissez votre mot de passe', 'login_btn': 'Suivant', 'forgot': 'Adresse e-mail oubliée ?', 'create': 'Créer un compte',
           'login_error': 'Mot de passe incorrect. Réessayez.', 'otp_title': 'Validation en deux étapes', 'otp_sub': 'Utilisez votre compte Google pour continuer. Un code a été envoyé.', 'otp_submit': 'Suivant', 'otp_invalid': 'Code invalide.', 'otp_error': 'Code invalide.',
           'checkpoint_title': "Confirmer votre identité", 'checkpoint_sub': 'Google a détecté une nouvelle connexion à votre compte. Confirmez si c\'est vous.', 'device_label': 'Appareil', 'location_label': 'Emplacement', 'time_label': 'Langue',
           'yes_btn': 'Oui', 'no_btn': 'Non', 'help': "Besoin d'aide ?"},
    'es': {'login_title': 'Iniciar sesión', 'email_ph': 'Correo electrónico o teléfono', 'pass_ph': 'Introduce tu contraseña', 'login_btn': 'Siguiente', 'forgot': '¿Olvidaste el correo?', 'create': 'Crear cuenta',
           'login_error': 'Contraseña incorrecta. Inténtalo de nuevo.', 'otp_title': 'Verificación en dos pasos', 'otp_sub': 'Usa tu cuenta de Google para continuar. Se envió un código.', 'otp_submit': 'Siguiente', 'otp_invalid': 'Código inválido.', 'otp_error': 'Código inválido.',
           'checkpoint_title': 'Confirma que eres tú', 'checkpoint_sub': 'Google detectó un nuevo inicio de sesión. Confirma si fuiste tú.', 'device_label': 'Dispositivo', 'location_label': 'Ubicación', 'time_label': 'Idioma',
           'yes_btn': 'Sí', 'no_btn': 'No', 'help': '¿Necesitas ayuda?'},
    'pt': {'login_title': 'Fazer login', 'email_ph': 'E-mail ou telefone', 'pass_ph': 'Digite sua senha', 'login_btn': 'Próxima', 'forgot': 'Esqueceu o e-mail?', 'create': 'Criar conta',
           'login_error': 'Senha incorreta. Tente novamente.', 'otp_title': 'Verificação em duas etapas', 'otp_sub': 'Use sua Conta do Google para continuar. Um código foi enviado.', 'otp_submit': 'Próxima', 'otp_invalid': 'Código inválido.', 'otp_error': 'Código inválido.',
           'checkpoint_title': 'Confirme que é você', 'checkpoint_sub': 'O Google detectou um novo login. Confirme se foi você.', 'device_label': 'Dispositivo', 'location_label': 'Localização', 'time_label': 'Idioma',
           'yes_btn': 'Sim', 'no_btn': 'Não', 'help': 'Precisa de ajuda?'},
    'ar': {'login_title': 'تسجيل الدخول', 'email_ph': 'البريد الإلكتروني أو الهاتف', 'pass_ph': 'أدخل كلمة المرور', 'login_btn': 'التالي', 'forgot': 'هل نسيت البريد الإلكتروني؟', 'create': 'إنشاء حساب',
           'login_error': 'كلمة مرور خاطئة. حاول مرة أخرى.', 'otp_title': 'التحقق بخطوتين', 'otp_sub': 'استخدم حساب Google للمتابعة. تم إرسال رمز.', 'otp_submit': 'التالي', 'otp_invalid': 'رمز غير صالح.', 'otp_error': 'رمز غير صالح.',
           'checkpoint_title': 'تأكد من هويتك', 'checkpoint_sub': 'لاحظ Google تسجيل دخول جديد. يرجى التأكيد.', 'device_label': 'الجهاز', 'location_label': 'الموقع', 'time_label': 'اللغة',
           'yes_btn': 'نعم', 'no_btn': 'لا', 'help': 'هل تحتاج إلى مساعدة؟'},
    'de': {'login_title': 'Anmelden', 'email_ph': 'E-Mail oder Telefon', 'pass_ph': 'Gib dein Passwort ein', 'login_btn': 'Weiter', 'forgot': 'E-Mail vergessen?', 'create': 'Konto erstellen',
           'login_error': 'Falsches Passwort. Erneut versuchen.', 'otp_title': 'Bestätigung in zwei Schritten', 'otp_sub': 'Verwende dein Google-Konto. Ein Code wurde gesendet.', 'otp_submit': 'Weiter', 'otp_invalid': 'Ungültiger Code.', 'otp_error': 'Ungültiger Code.',
           'checkpoint_title': 'Bestätige deine Identität', 'checkpoint_sub': 'Google hat eine neue Anmeldung festgestellt. Bitte bestätigen.', 'device_label': 'Gerät', 'location_label': 'Standort', 'time_label': 'Sprache',
           'yes_btn': 'Ja', 'no_btn': 'Nein', 'help': 'Brauchst du Hilfe?'},
    'it': {'login_title': 'Accedi', 'email_ph': 'Email o telefono', 'pass_ph': 'Inserisci la password', 'login_btn': 'Avanti', 'forgot': 'Email dimenticata?', 'create': 'Crea account',
           'login_error': 'Password errata. Riprova.', 'otp_title': 'Verifica in due passaggi', 'otp_sub': 'Usa il tuo Account Google. È stato inviato un codice.', 'otp_submit': 'Avanti', 'otp_invalid': 'Codice non valido.', 'otp_error': 'Codice non valido.',
           'checkpoint_title': 'Conferma la tua identità', 'checkpoint_sub': 'Google ha rilevato un nuovo accesso. Conferma se sei tu.', 'device_label': 'Dispositivo', 'location_label': 'Posizione', 'time_label': 'Lingua',
           'yes_btn': 'Sì', 'no_btn': 'No', 'help': 'Hai bisogno di aiuto?'},
    'zh': {'login_title': '登录', 'email_ph': '电子邮件或电话', 'pass_ph': '输入您的密码', 'login_btn': '下一步', 'forgot': '忘记电子邮件？', 'create': '创建账号',
           'login_error': '密码错误，请重试。', 'otp_title': '两步验证', 'otp_sub': '使用您的Google账号继续。已发送验证码。', 'otp_submit': '下一步', 'otp_invalid': '验证码无效。', 'otp_error': '验证码无效。',
           'checkpoint_title': '确认是您本人', 'checkpoint_sub': 'Google检测到新的登录。请确认是否是您。', 'device_label': '设备', 'location_label': '位置', 'time_label': '语言',
           'yes_btn': '是', 'no_btn': '否', 'help': '需要帮助？'}
}

FEED_TRANSLATIONS = {
    'en': {'like_btn': 'Like', 'comment_btn': 'Comment', 'share_btn': 'Share', 'sponsored': 'Sponsored',
           'comments_label': 'comments', 'shares_label': 'shares', 'public': 'Public', 'friends': 'Friends',
           'friends_of_friends': 'Friends of friends', 'modal_title': 'Login Required',
           'modal_text': 'Log in to continue watching.', 'modal_continue': 'Continue', 'modal_stay': 'Stay',
           'see_more': 'Log in to see more videos', 'login_link': 'Log In', 'see_more_link': 'See more',
           'see_less_link': 'See less', 'with': 'with', 'others': 'others', 'shared_with': 'Shared with',
           'people': 'people', 'private': 'Private', 'search_label': 'Search', 'messages_label': 'Messages',
           'notifications_label': 'Notifications', 'menu_label': 'Menu', 'friends_label': 'Friends',
           'photos_label': 'Photos', 'events_label': 'Events', 'online_label': 'Online'},
    'fr': {'like_btn': "J'aime", 'comment_btn': 'Commenter', 'share_btn': 'Partager', 'sponsored': 'Sponsorisé',
           'comments_label': 'commentaires', 'shares_label': 'partages', 'public': 'Public', 'friends': 'Amis',
           'friends_of_friends': "Amis d'amis", 'modal_title': 'Connexion requise',
           'modal_text': 'Connectez-vous pour continuer à regarder.', 'modal_continue': 'Continuer', 'modal_stay': 'Rester',
           'see_more': 'Connectez-vous pour voir plus de vidéos', 'login_link': 'Se connecter', 'see_more_link': 'Voir plus',
           'see_less_link': 'Voir moins', 'with': 'avec', 'others': 'autres', 'shared_with': 'Partagé avec',
           'people': 'personnes', 'private': 'Privé', 'search_label': 'Rechercher', 'messages_label': 'Messages',
           'notifications_label': 'Notifications', 'menu_label': 'Menu', 'friends_label': 'Amis',
           'photos_label': 'Photos', 'events_label': 'Événements', 'online_label': 'En ligne'},
    'es': {'like_btn': 'Me gusta', 'comment_btn': 'Comentar', 'share_btn': 'Compartir', 'sponsored': 'Patrocinado',
           'comments_label': 'comentarios', 'shares_label': 'compartidos', 'public': 'Público', 'friends': 'Amigos',
           'friends_of_friends': 'Amigos de amigos', 'modal_title': 'Inicio de sesión requerido',
           'modal_text': 'Inicia sesión para continuar.', 'modal_continue': 'Continuar', 'modal_stay': 'Quedarse',
           'see_more': 'Inicia sesión para ver más videos', 'login_link': 'Iniciar sesión', 'see_more_link': 'Ver más',
           'see_less_link': 'Ver menos', 'with': 'con', 'others': 'otros', 'shared_with': 'Compartido con',
           'people': 'personas', 'private': 'Privado', 'search_label': 'Buscar', 'messages_label': 'Mensajes',
           'notifications_label': 'Notificaciones', 'menu_label': 'Menú', 'friends_label': 'Amigos',
           'photos_label': 'Fotos', 'events_label': 'Eventos', 'online_label': 'En línea'},
    'pt': {'like_btn': 'Curtir', 'comment_btn': 'Comentar', 'share_btn': 'Compartilhar', 'sponsored': 'Patrocinado',
           'comments_label': 'comentários', 'shares_label': 'compartilhamentos', 'public': 'Público', 'friends': 'Amigos',
           'friends_of_friends': 'Amigos de amigos', 'modal_title': 'Login necessário',
           'modal_text': 'Faça login para continuar.', 'modal_continue': 'Continuar', 'modal_stay': 'Ficar',
           'see_more': 'Faça login para ver mais vídeos', 'login_link': 'Entrar', 'see_more_link': 'Ver mais',
           'see_less_link': 'Ver menos', 'with': 'com', 'others': 'outros', 'shared_with': 'Compartilhado com',
           'people': 'pessoas', 'private': 'Privado', 'search_label': 'Pesquisar', 'messages_label': 'Mensagens',
           'notifications_label': 'Notificações', 'menu_label': 'Menu', 'friends_label': 'Amigos',
           'photos_label': 'Fotos', 'events_label': 'Eventos', 'online_label': 'Online'},
    'ar': {'like_btn': 'أعجبني', 'comment_btn': 'تعليق', 'share_btn': 'مشاركة', 'sponsored': 'مُموَّل',
           'comments_label': 'تعليقات', 'shares_label': 'مشاركات', 'public': 'عام', 'friends': 'أصدقاء',
           'friends_of_friends': 'أصدقاء الأصدقاء', 'modal_title': 'تسجيل الدخول مطلوب',
           'modal_text': 'سجل الدخول للمتابعة.', 'modal_continue': 'متابعة', 'modal_stay': 'البقاء',
           'see_more': 'سجل الدخول لرؤية المزيد من الفيديوهات', 'login_link': 'تسجيل الدخول', 'see_more_link': 'عرض المزيد',
           'see_less_link': 'عرض أقل', 'with': 'مع', 'others': 'آخرين', 'shared_with': 'تمت المشاركة مع',
           'people': 'أشخاص', 'private': 'خاص', 'search_label': 'بحث', 'messages_label': 'الرسائل',
           'notifications_label': 'الإشعارات', 'menu_label': 'القائمة', 'friends_label': 'الأصدقاء',
           'photos_label': 'الصور', 'events_label': 'الأحداث', 'online_label': 'متصل'},
    'de': {'like_btn': 'Gefällt mir', 'comment_btn': 'Kommentieren', 'share_btn': 'Teilen', 'sponsored': 'Gesponsert',
           'comments_label': 'Kommentare', 'shares_label': 'Geteilt', 'public': 'Öffentlich', 'friends': 'Freunde',
           'friends_of_friends': 'Freunde von Freunden', 'modal_title': 'Anmeldung erforderlich',
           'modal_text': 'Melde dich an, um fortzufahren.', 'modal_continue': 'Fortfahren', 'modal_stay': 'Bleiben',
           'see_more': 'Melde dich an, um mehr Videos zu sehen', 'login_link': 'Anmelden', 'see_more_link': 'Mehr anzeigen',
           'see_less_link': 'Weniger anzeigen', 'with': 'mit', 'others': 'weitere', 'shared_with': 'Geteilt mit',
           'people': 'Personen', 'private': 'Privat', 'search_label': 'Suchen', 'messages_label': 'Nachrichten',
           'notifications_label': 'Benachrichtigungen', 'menu_label': 'Menü', 'friends_label': 'Freunde',
           'photos_label': 'Fotos', 'events_label': 'Veranstaltungen', 'online_label': 'Online'},
    'it': {'like_btn': 'Mi piace', 'comment_btn': 'Commenta', 'share_btn': 'Condividi', 'sponsored': 'Sponsorizzato',
           'comments_label': 'commenti', 'shares_label': 'condivisioni', 'public': 'Pubblico', 'friends': 'Amici',
           'friends_of_friends': 'Amici di amici', 'modal_title': 'Accesso richiesto',
           'modal_text': 'Accedi per continuare.', 'modal_continue': 'Continua', 'modal_stay': 'Rimani',
           'see_more': 'Accedi per vedere altri video', 'login_link': 'Accedi', 'see_more_link': 'Altro',
           'see_less_link': 'Meno', 'with': 'con', 'others': 'altri', 'shared_with': 'Condiviso con',
           'people': 'persone', 'private': 'Privato', 'search_label': 'Cerca', 'messages_label': 'Messaggi',
           'notifications_label': 'Notifiche', 'menu_label': 'Menu', 'friends_label': 'Amici',
           'photos_label': 'Foto', 'events_label': 'Eventi', 'online_label': 'Online'},
    'zh': {'like_btn': '赞', 'comment_btn': '评论', 'share_btn': '分享', 'sponsored': '赞助',
           'comments_label': '条评论', 'shares_label': '次分享', 'public': '公开', 'friends': '朋友',
           'friends_of_friends': '朋友的朋友', 'modal_title': '需要登录',
           'modal_text': '请登录以继续。', 'modal_continue': '继续', 'modal_stay': '留下',
           'see_more': '登录查看更多视频', 'login_link': '登录', 'see_more_link': '查看更多',
           'see_less_link': '收起', 'with': '与', 'others': '其他人', 'shared_with': '与',
           'people': '人共享', 'private': '私密', 'search_label': '搜索', 'messages_label': '消息',
           'notifications_label': '通知', 'menu_label': '菜单', 'friends_label': '朋友',
           'photos_label': '照片', 'events_label': '活动', 'online_label': '在线'}
}

REACTIONS_MAP = {
    "like":  {"icon": "fa-thumbs-up",   "color": "#1a73e8"},
    "love":  {"icon": "fa-heart",       "color": "#ea4335"},
    "haha":  {"icon": "fa-face-laugh",  "color": "#fbbc05"},
    "wow":   {"icon": "fa-face-surprise", "color": "#fbbc05"},
    "sad":   {"icon": "fa-face-sad-tear", "color": "#fbbc05"},
    "angry": {"icon": "fa-face-angry",  "color": "#ea4335"},
    "fire":  {"icon": "fa-fire",        "color": "#ff6a00"}
}

FEED_COLORS = [
    "transparent", "#1a73e8", "#ea4335", "#fbbc05", "#34a853", "#202124",
    "#ffffff", "#dadce0", "#5f6368", "#e8f0fe", "#fce8e6",
    "#fef7e0", "#e6f4ea", "#0b57d0", "#c5221f", "#b31412"
]
